export const BENEFICIARY_LOAD = "BENEFICIARY_LOAD";
export const BENEFICIARY_SUCCESS = "BENEFICIARY_SUCCESS";
export const BENEFICIARY_FAILURE = "BENEFICIARY_FAILURE";

export const SAGA_BENEFICIARY_LOAD = "SAGA_BENEFICIARY_LOAD";
export const SAGA_BENEFICIARY_SUCCESS = "SAGA_BENEFICIARY_SUCCESS";
export const SAGA_BENEFICIARY_FAILURE = "SAGA_BENEFICIARY_FAILURE";
export const SAGA_BENEFICIARY_LIST = "SAGA_BENEFICIARY_LIST";
export const SAGA_SEARCH = "SAGA_SEARCH";